# Generated by Django 5.2.1 on 2025-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('anniversaire', models.DateField()),
                ('temps_course', models.DurationField(blank=True, help_text='Durée de la course (format HH:MM:SS)', null=True)),
            ],
            options={
                'verbose_name': 'Coureur',
                'verbose_name_plural': 'Coureurs',
                'ordering': ['temps_course'],
            },
        ),
    ]
