# Generated by Django 5.2.1 on 2025-06-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coureur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Coureur', 'verbose_name_plural': 'Coureurs'},
        ),
        migrations.RemoveField(
            model_name='coureur',
            name='temps_course',
        ),
        migrations.AlterField(
            model_name='coureur',
            name='anniversaire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coureur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossard', models.IntegerField(help_text='Numéro de dossard', unique=True)),
                ('temps_course', models.DurationField(blank=True, help_text='Durée de la course (format HH:MM:SS)', null=True)),
                ('coureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='website.coureur')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['temps_course'],
            },
        ),
    ]
