# Generated by Django 5.2.1 on 2025-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_coureur_options_remove_coureur_temps_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together={('coureur',)},
        ),
        migrations.AddField(
            model_name='coureur',
            name='dossard',
            field=models.IntegerField(default=1, help_text='Numéro de dossard', unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='dossard',
        ),
    ]
