# Generated by Django 5.2.1 on 2025-06-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_resultat_unique_together_coureur_dossard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la course', max_length=200, unique=True)),
                ('date_course', models.DateField(help_text='Date')),
                ('description', models.TextField(blank=True, null=True)),
                ('deniv', models.IntegerField(blank=True)),
                ('distance', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-date_course', 'nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultat',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='website.course'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together={('coureur', 'course')},
        ),
    ]
