# Generated by Django 5.2.1 on 2025-06-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_course_alter_resultat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together={('coureur',)},
        ),
        migrations.AddField(
            model_name='coureur',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='website.course'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='course',
        ),
    ]
