# Generated by Django 5.2.1 on 2025-06-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_resultat_unique_together_coureur_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureur',
            name='temps_course',
            field=models.DurationField(blank=True, help_text='Durée de la course (format HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='coureur',
            name='course',
            field=models.ForeignKey(blank=True, help_text='La course à laquelle ce coureur participe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='website.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='deniv',
            field=models.IntegerField(blank=True, help_text='Dénivelé positif en mètres', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='distance',
            field=models.IntegerField(blank=True, help_text='Distance en kilomètres', null=True),
        ),
        migrations.DeleteModel(
            name='Resultat',
        ),
    ]
