# Generated by Django 5.2.1 on 2025-06-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_coureur_temps_course_alter_coureur_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureur',
            name='course',
            field=models.ForeignKey(default=1, help_text='La course à laquelle ce coureur est inscrit.', on_delete=django.db.models.deletion.PROTECT, related_name='coureurs', to='website.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coureur',
            name='dossard',
            field=models.IntegerField(blank=True, help_text='Numéro de dossard pour cette course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='deniv',
            field=models.IntegerField(blank=True, help_text='Dénivelé positif (m)', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='distance',
            field=models.IntegerField(blank=True, help_text='Distance (km)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coureur',
            unique_together={('course', 'dossard')},
        ),
    ]
