# Generated by Django 5.2.1 on 2025-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_coureur_course_alter_coureur_dossard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureur',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default=1, help_text='Sexe du coureur', max_length=1),
            preserve_default=False,
        ),
    ]
