# Generated by Django 5.2.1 on 2025-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_coureur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dossard_end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='dossard_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
