# Generated by Django 5.2.1 on 2025-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_course_dossard_end_course_dossard_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coureur',
            old_name='anniversaire',
            new_name='date_naissance',
        ),
        migrations.AddField(
            model_name='coureur',
            name='CP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='date_inscription',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='emailcontact',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='repas',
            field=models.IntegerField(default=0, help_text='Nombre de repas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coureur',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
