# Generated by Django 5.2.1 on 2025-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_anniversaire_coureur_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
