# Generated by Django 5.2.1 on 2025-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_coureur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='extracts/')),
            ],
        ),
        migrations.AlterField(
            model_name='coureur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], help_text='Sexe du coureur', max_length=1),
        ),
    ]
