# Generated by Django 5.2.1 on 2025-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_extract_alter_coureur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureur',
            name='emailcontact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
