# Generated by Django 6.0.2 on 2026-02-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_coureur_emailcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text='e.g. 2025', unique=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='website/posters/')),
                ('participants', models.PositiveIntegerField(default=0)),
                ('benevoles', models.PositiveIntegerField(default=0)),
                ('resultats_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
    ]
