# Generated by Django 6.0.2 on 2026-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_coureur_emailcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='heure_depart',
            field=models.TimeField(blank=True, help_text='Heure de départ de la course (HH:MM:SS)', null=True),
        ),
    ]
