# Generated by Django 6.0.2 on 2026-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_course_heure_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureur',
            name='position_generale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coureur',
            name='position_par_categorie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
