# Generated by Django 6.0.2 on 2026-02-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_editions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editions',
            new_name='Edition',
        ),
    ]
