# Generated by Django 6.0.2 on 2026-02-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_coureur_position_generale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coureur',
            name='repas',
        ),
    ]
