# Generated by Django 5.2.1 on 2026-02-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_editions_edition'),
        ('website', '0016_remove_coureur_repas'),
    ]

    operations = [
    ]
