# Generated by Django 6.0.2 on 2026-02-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_editions_edition'),
        ('website', '0016_remove_coureur_repas'),
    ]

    operations = [
    ]
