# Generated by Django 5.2.1 on 2026-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_merge_20260227_1622'),
        ('website', '0017_merge_20260227_1811'),
    ]

    operations = [
    ]
