# Generated by Django 6.0.2 on 2026-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_merge_20260227_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('CP', models.IntegerField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
