# Generated by Django 6.0.2 on 2026-03-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ravito',
            field=models.IntegerField(blank=True, help_text='Nombre de ravitaillements', null=True),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='CP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='telephone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benevole',
            name='ville',
            field=models.CharField(blank=True, null=True),
        ),
    ]
