# Generated by Django 6.0.2 on 2026-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_course_ravito_alter_benevole_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age_limite',
            field=models.CharField(blank=True, help_text='Age limite', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='retrait_dossard',
            field=models.CharField(blank=True, help_text='Heure retrait dossards', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Course', 'Course'), ('Marche', 'Marche')], default='Course', help_text='Type de course'),
            preserve_default=False,
        ),
    ]
