# Generated by Django 6.0.2 on 2026-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_course_age_limite_course_retrait_dossard_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, help_text="entrer '#fffff' pour la couleur", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='gpx_file',
            field=models.FileField(blank=True, null=True, upload_to='gpx/'),
        ),
        migrations.AddField(
            model_name='course',
            name='header',
            field=models.CharField(blank=True, help_text='adresse du haut de page', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='matos_conseille',
            field=models.CharField(blank=True, help_text='Matériel conseillé', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='matos_obligatoire',
            field=models.CharField(blank=True, help_text='Matériel obligatoire', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='tour_des_fontaines', unique=True),
            preserve_default=False,
        ),
    ]
