# Generated by Django 6.0.2 on 2026-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='header',
            field=models.CharField(blank=True, help_text='adresse du haut de page', null=True),
        ),
    ]
