# Generated by Django 6.0.2 on 2026-03-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='header',
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, help_text='Video pour le header de la course', null=True, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='gpx_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/gpx/'),
        ),
    ]
