# Generated by Django 5.0.3 on 2025-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee', models.DateField(null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('dossard', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coureur',
                'ordering': ['heure_arrivee'],
            },
        ),
    ]
